export interface Plot {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  type: string;
  subType: string;
  totalArea: number;
  areaInSqFt: number;
  dimensions: string;
  length: number;
  breadth: number;
  price: number;
  pricePerSqYard: number | null;
  pricePerAcre?: number;
  facing: string;
  openSides: number;
  cornerPlot: boolean;
  roadWidth: string;
  boundaryWall: string;
  gatedLayout: boolean;
  layoutName: string | null;
  zoning: string;
  approvingAuthority: string;
  reraApproved: boolean;
  clearTitle: boolean;
  encumbranceCertificate: string;
  ownershipType: string;
  maxPermissibleFloors: string;
  fsi: number | null;
  water: boolean;
  electricity: boolean;
  drainage: boolean;
  roadType: string;
  streetLights: boolean;
  address: string;
  locality: string;
  city: string;
  state: string;
  pincode: string;
  description: string;
  infrastructureHighlights: string[];
  images: string[];
  featured: boolean;
  status: string;
}
